// Regenerates src/leagues/teamsData.ts from ESPN's /teams endpoint.
//
// Why bundle this? ESPN's teams-LIST endpoint does not send CORS headers, so a
// browser cannot read it. Team rosters are small, stable reference data, so we
// fetch them here (Node, no CORS) and commit the result. Live standings/games
// still come from the CORS-enabled /teams/{id} and /schedule endpoints.
//
// Run: node scripts/generate-teams.mjs
import { writeFile } from "node:fs/promises";

const BASE = "https://site.api.espn.com/apis/site/v2/sports";

// Keep in sync with src/leagues/registry.ts
const LEAGUES = [
  { id: "nba", sport: "basketball", league: "nba" },
  { id: "wnba", sport: "basketball", league: "wnba" },
  { id: "nfl", sport: "football", league: "nfl" },
  { id: "mlb", sport: "baseball", league: "mlb" },
  { id: "nhl", sport: "hockey", league: "nhl" },
  { id: "mls", sport: "soccer", league: "usa.1" },
];

async function fetchTeams(cfg) {
  const res = await fetch(`${BASE}/${cfg.sport}/${cfg.league}/teams`);
  if (!res.ok) throw new Error(`${cfg.id}: ${res.status}`);
  const data = await res.json();
  const entries = data.sports?.[0]?.leagues?.[0]?.teams ?? [];
  return entries
    .map((t) => ({
      id: t.team.id,
      leagueId: cfg.id,
      name: t.team.displayName,
      abbreviation: t.team.abbreviation,
      logoUrl: t.team.logos?.[0]?.href,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

const byLeague = {};
for (const cfg of LEAGUES) {
  byLeague[cfg.id] = await fetchTeams(cfg);
  console.error(`${cfg.id}: ${byLeague[cfg.id].length} teams`);
}

const header = `// AUTO-GENERATED by scripts/generate-teams.mjs — do not edit by hand.
// Bundled team rosters per league. ESPN's /teams list endpoint is not
// CORS-enabled, so search filters this committed reference data client-side.
// Regenerate with: node scripts/generate-teams.mjs
import type { Team } from "../domain/types";
`;

const body = `export const TEAMS_BY_LEAGUE: Record<string, Team[]> = ${JSON.stringify(byLeague, null, 2)};\n`;

await writeFile(
  new URL("../src/leagues/teamsData.ts", import.meta.url),
  header + "\n" + body,
);
console.error("wrote src/leagues/teamsData.ts");
