// AUTO-GENERATED by scripts/generate-teams.mjs — do not edit by hand.
// Bundled team rosters per league. ESPN's /teams list endpoint is not
// CORS-enabled, so search filters this committed reference data client-side.
// Regenerate with: node scripts/generate-teams.mjs
import type { Team } from "../domain/types";

export const TEAMS_BY_LEAGUE: Record<string, Team[]> = {
  "nba": [
    {
      "id": "1",
      "leagueId": "nba",
      "name": "Atlanta Hawks",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png"
    },
    {
      "id": "2",
      "leagueId": "nba",
      "name": "Boston Celtics",
      "abbreviation": "BOS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png"
    },
    {
      "id": "17",
      "leagueId": "nba",
      "name": "Brooklyn Nets",
      "abbreviation": "BKN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png"
    },
    {
      "id": "30",
      "leagueId": "nba",
      "name": "Charlotte Hornets",
      "abbreviation": "CHA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png"
    },
    {
      "id": "4",
      "leagueId": "nba",
      "name": "Chicago Bulls",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png"
    },
    {
      "id": "5",
      "leagueId": "nba",
      "name": "Cleveland Cavaliers",
      "abbreviation": "CLE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png"
    },
    {
      "id": "6",
      "leagueId": "nba",
      "name": "Dallas Mavericks",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png"
    },
    {
      "id": "7",
      "leagueId": "nba",
      "name": "Denver Nuggets",
      "abbreviation": "DEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/den.png"
    },
    {
      "id": "8",
      "leagueId": "nba",
      "name": "Detroit Pistons",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/det.png"
    },
    {
      "id": "9",
      "leagueId": "nba",
      "name": "Golden State Warriors",
      "abbreviation": "GS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png"
    },
    {
      "id": "10",
      "leagueId": "nba",
      "name": "Houston Rockets",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png"
    },
    {
      "id": "11",
      "leagueId": "nba",
      "name": "Indiana Pacers",
      "abbreviation": "IND",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png"
    },
    {
      "id": "12",
      "leagueId": "nba",
      "name": "LA Clippers",
      "abbreviation": "LAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png"
    },
    {
      "id": "13",
      "leagueId": "nba",
      "name": "Los Angeles Lakers",
      "abbreviation": "LAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png"
    },
    {
      "id": "29",
      "leagueId": "nba",
      "name": "Memphis Grizzlies",
      "abbreviation": "MEM",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png"
    },
    {
      "id": "14",
      "leagueId": "nba",
      "name": "Miami Heat",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png"
    },
    {
      "id": "15",
      "leagueId": "nba",
      "name": "Milwaukee Bucks",
      "abbreviation": "MIL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png"
    },
    {
      "id": "16",
      "leagueId": "nba",
      "name": "Minnesota Timberwolves",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/min.png"
    },
    {
      "id": "3",
      "leagueId": "nba",
      "name": "New Orleans Pelicans",
      "abbreviation": "NO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/no.png"
    },
    {
      "id": "18",
      "leagueId": "nba",
      "name": "New York Knicks",
      "abbreviation": "NY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png"
    },
    {
      "id": "25",
      "leagueId": "nba",
      "name": "Oklahoma City Thunder",
      "abbreviation": "OKC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png"
    },
    {
      "id": "19",
      "leagueId": "nba",
      "name": "Orlando Magic",
      "abbreviation": "ORL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png"
    },
    {
      "id": "20",
      "leagueId": "nba",
      "name": "Philadelphia 76ers",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png"
    },
    {
      "id": "21",
      "leagueId": "nba",
      "name": "Phoenix Suns",
      "abbreviation": "PHX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png"
    },
    {
      "id": "22",
      "leagueId": "nba",
      "name": "Portland Trail Blazers",
      "abbreviation": "POR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/por.png"
    },
    {
      "id": "23",
      "leagueId": "nba",
      "name": "Sacramento Kings",
      "abbreviation": "SAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png"
    },
    {
      "id": "24",
      "leagueId": "nba",
      "name": "San Antonio Spurs",
      "abbreviation": "SA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png"
    },
    {
      "id": "28",
      "leagueId": "nba",
      "name": "Toronto Raptors",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png"
    },
    {
      "id": "26",
      "leagueId": "nba",
      "name": "Utah Jazz",
      "abbreviation": "UTAH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png"
    },
    {
      "id": "27",
      "leagueId": "nba",
      "name": "Washington Wizards",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png"
    }
  ],
  "nfl": [
    {
      "id": "22",
      "leagueId": "nfl",
      "name": "Arizona Cardinals",
      "abbreviation": "ARI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png"
    },
    {
      "id": "1",
      "leagueId": "nfl",
      "name": "Atlanta Falcons",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png"
    },
    {
      "id": "33",
      "leagueId": "nfl",
      "name": "Baltimore Ravens",
      "abbreviation": "BAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png"
    },
    {
      "id": "2",
      "leagueId": "nfl",
      "name": "Buffalo Bills",
      "abbreviation": "BUF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png"
    },
    {
      "id": "29",
      "leagueId": "nfl",
      "name": "Carolina Panthers",
      "abbreviation": "CAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png"
    },
    {
      "id": "3",
      "leagueId": "nfl",
      "name": "Chicago Bears",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png"
    },
    {
      "id": "4",
      "leagueId": "nfl",
      "name": "Cincinnati Bengals",
      "abbreviation": "CIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png"
    },
    {
      "id": "5",
      "leagueId": "nfl",
      "name": "Cleveland Browns",
      "abbreviation": "CLE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png"
    },
    {
      "id": "6",
      "leagueId": "nfl",
      "name": "Dallas Cowboys",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png"
    },
    {
      "id": "7",
      "leagueId": "nfl",
      "name": "Denver Broncos",
      "abbreviation": "DEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png"
    },
    {
      "id": "8",
      "leagueId": "nfl",
      "name": "Detroit Lions",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png"
    },
    {
      "id": "9",
      "leagueId": "nfl",
      "name": "Green Bay Packers",
      "abbreviation": "GB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png"
    },
    {
      "id": "34",
      "leagueId": "nfl",
      "name": "Houston Texans",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
    },
    {
      "id": "11",
      "leagueId": "nfl",
      "name": "Indianapolis Colts",
      "abbreviation": "IND",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png"
    },
    {
      "id": "30",
      "leagueId": "nfl",
      "name": "Jacksonville Jaguars",
      "abbreviation": "JAX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png"
    },
    {
      "id": "12",
      "leagueId": "nfl",
      "name": "Kansas City Chiefs",
      "abbreviation": "KC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png"
    },
    {
      "id": "13",
      "leagueId": "nfl",
      "name": "Las Vegas Raiders",
      "abbreviation": "LV",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png"
    },
    {
      "id": "24",
      "leagueId": "nfl",
      "name": "Los Angeles Chargers",
      "abbreviation": "LAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png"
    },
    {
      "id": "14",
      "leagueId": "nfl",
      "name": "Los Angeles Rams",
      "abbreviation": "LAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"
    },
    {
      "id": "15",
      "leagueId": "nfl",
      "name": "Miami Dolphins",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png"
    },
    {
      "id": "16",
      "leagueId": "nfl",
      "name": "Minnesota Vikings",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png"
    },
    {
      "id": "17",
      "leagueId": "nfl",
      "name": "New England Patriots",
      "abbreviation": "NE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png"
    },
    {
      "id": "18",
      "leagueId": "nfl",
      "name": "New Orleans Saints",
      "abbreviation": "NO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png"
    },
    {
      "id": "19",
      "leagueId": "nfl",
      "name": "New York Giants",
      "abbreviation": "NYG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png"
    },
    {
      "id": "20",
      "leagueId": "nfl",
      "name": "New York Jets",
      "abbreviation": "NYJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png"
    },
    {
      "id": "21",
      "leagueId": "nfl",
      "name": "Philadelphia Eagles",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png"
    },
    {
      "id": "23",
      "leagueId": "nfl",
      "name": "Pittsburgh Steelers",
      "abbreviation": "PIT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png"
    },
    {
      "id": "25",
      "leagueId": "nfl",
      "name": "San Francisco 49ers",
      "abbreviation": "SF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png"
    },
    {
      "id": "26",
      "leagueId": "nfl",
      "name": "Seattle Seahawks",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png"
    },
    {
      "id": "27",
      "leagueId": "nfl",
      "name": "Tampa Bay Buccaneers",
      "abbreviation": "TB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png"
    },
    {
      "id": "10",
      "leagueId": "nfl",
      "name": "Tennessee Titans",
      "abbreviation": "TEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png"
    },
    {
      "id": "28",
      "leagueId": "nfl",
      "name": "Washington Commanders",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"
    }
  ]
};
