// AUTO-GENERATED by scripts/generate-teams.mjs — do not edit by hand.
// Bundled team rosters per league. ESPN's /teams list endpoint is not
// CORS-enabled, so search filters this committed reference data client-side.
// Regenerate with: node scripts/generate-teams.mjs
import type { Team } from "../domain/types";

export const TEAMS_BY_LEAGUE: Record<string, Team[]> = {
  "nba": [
    {
      "id": "1",
      "leagueId": "nba",
      "name": "Atlanta Hawks",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png"
    },
    {
      "id": "2",
      "leagueId": "nba",
      "name": "Boston Celtics",
      "abbreviation": "BOS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png"
    },
    {
      "id": "17",
      "leagueId": "nba",
      "name": "Brooklyn Nets",
      "abbreviation": "BKN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png"
    },
    {
      "id": "30",
      "leagueId": "nba",
      "name": "Charlotte Hornets",
      "abbreviation": "CHA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png"
    },
    {
      "id": "4",
      "leagueId": "nba",
      "name": "Chicago Bulls",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png"
    },
    {
      "id": "5",
      "leagueId": "nba",
      "name": "Cleveland Cavaliers",
      "abbreviation": "CLE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png"
    },
    {
      "id": "6",
      "leagueId": "nba",
      "name": "Dallas Mavericks",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png"
    },
    {
      "id": "7",
      "leagueId": "nba",
      "name": "Denver Nuggets",
      "abbreviation": "DEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/den.png"
    },
    {
      "id": "8",
      "leagueId": "nba",
      "name": "Detroit Pistons",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/det.png"
    },
    {
      "id": "9",
      "leagueId": "nba",
      "name": "Golden State Warriors",
      "abbreviation": "GS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png"
    },
    {
      "id": "10",
      "leagueId": "nba",
      "name": "Houston Rockets",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png"
    },
    {
      "id": "11",
      "leagueId": "nba",
      "name": "Indiana Pacers",
      "abbreviation": "IND",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png"
    },
    {
      "id": "12",
      "leagueId": "nba",
      "name": "LA Clippers",
      "abbreviation": "LAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png"
    },
    {
      "id": "13",
      "leagueId": "nba",
      "name": "Los Angeles Lakers",
      "abbreviation": "LAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png"
    },
    {
      "id": "29",
      "leagueId": "nba",
      "name": "Memphis Grizzlies",
      "abbreviation": "MEM",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png"
    },
    {
      "id": "14",
      "leagueId": "nba",
      "name": "Miami Heat",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png"
    },
    {
      "id": "15",
      "leagueId": "nba",
      "name": "Milwaukee Bucks",
      "abbreviation": "MIL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png"
    },
    {
      "id": "16",
      "leagueId": "nba",
      "name": "Minnesota Timberwolves",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/min.png"
    },
    {
      "id": "3",
      "leagueId": "nba",
      "name": "New Orleans Pelicans",
      "abbreviation": "NO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/no.png"
    },
    {
      "id": "18",
      "leagueId": "nba",
      "name": "New York Knicks",
      "abbreviation": "NY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png"
    },
    {
      "id": "25",
      "leagueId": "nba",
      "name": "Oklahoma City Thunder",
      "abbreviation": "OKC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png"
    },
    {
      "id": "19",
      "leagueId": "nba",
      "name": "Orlando Magic",
      "abbreviation": "ORL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png"
    },
    {
      "id": "20",
      "leagueId": "nba",
      "name": "Philadelphia 76ers",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png"
    },
    {
      "id": "21",
      "leagueId": "nba",
      "name": "Phoenix Suns",
      "abbreviation": "PHX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png"
    },
    {
      "id": "22",
      "leagueId": "nba",
      "name": "Portland Trail Blazers",
      "abbreviation": "POR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/por.png"
    },
    {
      "id": "23",
      "leagueId": "nba",
      "name": "Sacramento Kings",
      "abbreviation": "SAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png"
    },
    {
      "id": "24",
      "leagueId": "nba",
      "name": "San Antonio Spurs",
      "abbreviation": "SA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png"
    },
    {
      "id": "28",
      "leagueId": "nba",
      "name": "Toronto Raptors",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png"
    },
    {
      "id": "26",
      "leagueId": "nba",
      "name": "Utah Jazz",
      "abbreviation": "UTAH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png"
    },
    {
      "id": "27",
      "leagueId": "nba",
      "name": "Washington Wizards",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png"
    }
  ],
  "wnba": [
    {
      "id": "20",
      "leagueId": "wnba",
      "name": "Atlanta Dream",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/atl.png"
    },
    {
      "id": "19",
      "leagueId": "wnba",
      "name": "Chicago Sky",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/chi.png"
    },
    {
      "id": "18",
      "leagueId": "wnba",
      "name": "Connecticut Sun",
      "abbreviation": "CON",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/con.png"
    },
    {
      "id": "3",
      "leagueId": "wnba",
      "name": "Dallas Wings",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/dal.png"
    },
    {
      "id": "129689",
      "leagueId": "wnba",
      "name": "Golden State Valkyries",
      "abbreviation": "GS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/gs.png"
    },
    {
      "id": "5",
      "leagueId": "wnba",
      "name": "Indiana Fever",
      "abbreviation": "IND",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/ind.png"
    },
    {
      "id": "17",
      "leagueId": "wnba",
      "name": "Las Vegas Aces",
      "abbreviation": "LV",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/lv.png"
    },
    {
      "id": "6",
      "leagueId": "wnba",
      "name": "Los Angeles Sparks",
      "abbreviation": "LA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/la.png"
    },
    {
      "id": "8",
      "leagueId": "wnba",
      "name": "Minnesota Lynx",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/min.png"
    },
    {
      "id": "9",
      "leagueId": "wnba",
      "name": "New York Liberty",
      "abbreviation": "NY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/ny.png"
    },
    {
      "id": "11",
      "leagueId": "wnba",
      "name": "Phoenix Mercury",
      "abbreviation": "PHX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/phx.png"
    },
    {
      "id": "132052",
      "leagueId": "wnba",
      "name": "Portland Fire",
      "abbreviation": "POR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/por.png"
    },
    {
      "id": "14",
      "leagueId": "wnba",
      "name": "Seattle Storm",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/sea.png"
    },
    {
      "id": "131935",
      "leagueId": "wnba",
      "name": "Toronto Tempo",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/tor.png"
    },
    {
      "id": "16",
      "leagueId": "wnba",
      "name": "Washington Mystics",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/wnba/500/wsh.png"
    }
  ],
  "nfl": [
    {
      "id": "22",
      "leagueId": "nfl",
      "name": "Arizona Cardinals",
      "abbreviation": "ARI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png"
    },
    {
      "id": "1",
      "leagueId": "nfl",
      "name": "Atlanta Falcons",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png"
    },
    {
      "id": "33",
      "leagueId": "nfl",
      "name": "Baltimore Ravens",
      "abbreviation": "BAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png"
    },
    {
      "id": "2",
      "leagueId": "nfl",
      "name": "Buffalo Bills",
      "abbreviation": "BUF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png"
    },
    {
      "id": "29",
      "leagueId": "nfl",
      "name": "Carolina Panthers",
      "abbreviation": "CAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png"
    },
    {
      "id": "3",
      "leagueId": "nfl",
      "name": "Chicago Bears",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png"
    },
    {
      "id": "4",
      "leagueId": "nfl",
      "name": "Cincinnati Bengals",
      "abbreviation": "CIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png"
    },
    {
      "id": "5",
      "leagueId": "nfl",
      "name": "Cleveland Browns",
      "abbreviation": "CLE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png"
    },
    {
      "id": "6",
      "leagueId": "nfl",
      "name": "Dallas Cowboys",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png"
    },
    {
      "id": "7",
      "leagueId": "nfl",
      "name": "Denver Broncos",
      "abbreviation": "DEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png"
    },
    {
      "id": "8",
      "leagueId": "nfl",
      "name": "Detroit Lions",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png"
    },
    {
      "id": "9",
      "leagueId": "nfl",
      "name": "Green Bay Packers",
      "abbreviation": "GB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png"
    },
    {
      "id": "34",
      "leagueId": "nfl",
      "name": "Houston Texans",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
    },
    {
      "id": "11",
      "leagueId": "nfl",
      "name": "Indianapolis Colts",
      "abbreviation": "IND",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png"
    },
    {
      "id": "30",
      "leagueId": "nfl",
      "name": "Jacksonville Jaguars",
      "abbreviation": "JAX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png"
    },
    {
      "id": "12",
      "leagueId": "nfl",
      "name": "Kansas City Chiefs",
      "abbreviation": "KC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png"
    },
    {
      "id": "13",
      "leagueId": "nfl",
      "name": "Las Vegas Raiders",
      "abbreviation": "LV",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png"
    },
    {
      "id": "24",
      "leagueId": "nfl",
      "name": "Los Angeles Chargers",
      "abbreviation": "LAC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png"
    },
    {
      "id": "14",
      "leagueId": "nfl",
      "name": "Los Angeles Rams",
      "abbreviation": "LAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"
    },
    {
      "id": "15",
      "leagueId": "nfl",
      "name": "Miami Dolphins",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png"
    },
    {
      "id": "16",
      "leagueId": "nfl",
      "name": "Minnesota Vikings",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png"
    },
    {
      "id": "17",
      "leagueId": "nfl",
      "name": "New England Patriots",
      "abbreviation": "NE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png"
    },
    {
      "id": "18",
      "leagueId": "nfl",
      "name": "New Orleans Saints",
      "abbreviation": "NO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png"
    },
    {
      "id": "19",
      "leagueId": "nfl",
      "name": "New York Giants",
      "abbreviation": "NYG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png"
    },
    {
      "id": "20",
      "leagueId": "nfl",
      "name": "New York Jets",
      "abbreviation": "NYJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png"
    },
    {
      "id": "21",
      "leagueId": "nfl",
      "name": "Philadelphia Eagles",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png"
    },
    {
      "id": "23",
      "leagueId": "nfl",
      "name": "Pittsburgh Steelers",
      "abbreviation": "PIT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png"
    },
    {
      "id": "25",
      "leagueId": "nfl",
      "name": "San Francisco 49ers",
      "abbreviation": "SF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png"
    },
    {
      "id": "26",
      "leagueId": "nfl",
      "name": "Seattle Seahawks",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png"
    },
    {
      "id": "27",
      "leagueId": "nfl",
      "name": "Tampa Bay Buccaneers",
      "abbreviation": "TB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png"
    },
    {
      "id": "10",
      "leagueId": "nfl",
      "name": "Tennessee Titans",
      "abbreviation": "TEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png"
    },
    {
      "id": "28",
      "leagueId": "nfl",
      "name": "Washington Commanders",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"
    }
  ],
  "mlb": [
    {
      "id": "29",
      "leagueId": "mlb",
      "name": "Arizona Diamondbacks",
      "abbreviation": "ARI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/ari.png"
    },
    {
      "id": "11",
      "leagueId": "mlb",
      "name": "Athletics",
      "abbreviation": "ATH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/ath.png"
    },
    {
      "id": "15",
      "leagueId": "mlb",
      "name": "Atlanta Braves",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png"
    },
    {
      "id": "1",
      "leagueId": "mlb",
      "name": "Baltimore Orioles",
      "abbreviation": "BAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/bal.png"
    },
    {
      "id": "2",
      "leagueId": "mlb",
      "name": "Boston Red Sox",
      "abbreviation": "BOS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/bos.png"
    },
    {
      "id": "16",
      "leagueId": "mlb",
      "name": "Chicago Cubs",
      "abbreviation": "CHC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/chc.png"
    },
    {
      "id": "4",
      "leagueId": "mlb",
      "name": "Chicago White Sox",
      "abbreviation": "CHW",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/chw.png"
    },
    {
      "id": "17",
      "leagueId": "mlb",
      "name": "Cincinnati Reds",
      "abbreviation": "CIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png"
    },
    {
      "id": "5",
      "leagueId": "mlb",
      "name": "Cleveland Guardians",
      "abbreviation": "CLE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/cle.png"
    },
    {
      "id": "27",
      "leagueId": "mlb",
      "name": "Colorado Rockies",
      "abbreviation": "COL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/col.png"
    },
    {
      "id": "6",
      "leagueId": "mlb",
      "name": "Detroit Tigers",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/det.png"
    },
    {
      "id": "18",
      "leagueId": "mlb",
      "name": "Houston Astros",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png"
    },
    {
      "id": "7",
      "leagueId": "mlb",
      "name": "Kansas City Royals",
      "abbreviation": "KC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png"
    },
    {
      "id": "3",
      "leagueId": "mlb",
      "name": "Los Angeles Angels",
      "abbreviation": "LAA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/laa.png"
    },
    {
      "id": "19",
      "leagueId": "mlb",
      "name": "Los Angeles Dodgers",
      "abbreviation": "LAD",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png"
    },
    {
      "id": "28",
      "leagueId": "mlb",
      "name": "Miami Marlins",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png"
    },
    {
      "id": "8",
      "leagueId": "mlb",
      "name": "Milwaukee Brewers",
      "abbreviation": "MIL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/mil.png"
    },
    {
      "id": "9",
      "leagueId": "mlb",
      "name": "Minnesota Twins",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/min.png"
    },
    {
      "id": "21",
      "leagueId": "mlb",
      "name": "New York Mets",
      "abbreviation": "NYM",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png"
    },
    {
      "id": "10",
      "leagueId": "mlb",
      "name": "New York Yankees",
      "abbreviation": "NYY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png"
    },
    {
      "id": "22",
      "leagueId": "mlb",
      "name": "Philadelphia Phillies",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png"
    },
    {
      "id": "23",
      "leagueId": "mlb",
      "name": "Pittsburgh Pirates",
      "abbreviation": "PIT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/pit.png"
    },
    {
      "id": "25",
      "leagueId": "mlb",
      "name": "San Diego Padres",
      "abbreviation": "SD",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png"
    },
    {
      "id": "26",
      "leagueId": "mlb",
      "name": "San Francisco Giants",
      "abbreviation": "SF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/sf.png"
    },
    {
      "id": "12",
      "leagueId": "mlb",
      "name": "Seattle Mariners",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/sea.png"
    },
    {
      "id": "24",
      "leagueId": "mlb",
      "name": "St. Louis Cardinals",
      "abbreviation": "STL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png"
    },
    {
      "id": "30",
      "leagueId": "mlb",
      "name": "Tampa Bay Rays",
      "abbreviation": "TB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/tb.png"
    },
    {
      "id": "13",
      "leagueId": "mlb",
      "name": "Texas Rangers",
      "abbreviation": "TEX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/tex.png"
    },
    {
      "id": "14",
      "leagueId": "mlb",
      "name": "Toronto Blue Jays",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/tor.png"
    },
    {
      "id": "20",
      "leagueId": "mlb",
      "name": "Washington Nationals",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png"
    }
  ],
  "nhl": [
    {
      "id": "25",
      "leagueId": "nhl",
      "name": "Anaheim Ducks",
      "abbreviation": "ANA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/ana.png"
    },
    {
      "id": "1",
      "leagueId": "nhl",
      "name": "Boston Bruins",
      "abbreviation": "BOS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/bos.png"
    },
    {
      "id": "2",
      "leagueId": "nhl",
      "name": "Buffalo Sabres",
      "abbreviation": "BUF",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/buf.png"
    },
    {
      "id": "3",
      "leagueId": "nhl",
      "name": "Calgary Flames",
      "abbreviation": "CGY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/cgy.png"
    },
    {
      "id": "7",
      "leagueId": "nhl",
      "name": "Carolina Hurricanes",
      "abbreviation": "CAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/car.png"
    },
    {
      "id": "4",
      "leagueId": "nhl",
      "name": "Chicago Blackhawks",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/chi.png"
    },
    {
      "id": "17",
      "leagueId": "nhl",
      "name": "Colorado Avalanche",
      "abbreviation": "COL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/col.png"
    },
    {
      "id": "29",
      "leagueId": "nhl",
      "name": "Columbus Blue Jackets",
      "abbreviation": "CBJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/cbj.png"
    },
    {
      "id": "9",
      "leagueId": "nhl",
      "name": "Dallas Stars",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/dal.png"
    },
    {
      "id": "5",
      "leagueId": "nhl",
      "name": "Detroit Red Wings",
      "abbreviation": "DET",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/det.png"
    },
    {
      "id": "6",
      "leagueId": "nhl",
      "name": "Edmonton Oilers",
      "abbreviation": "EDM",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/edm.png"
    },
    {
      "id": "26",
      "leagueId": "nhl",
      "name": "Florida Panthers",
      "abbreviation": "FLA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/fla.png"
    },
    {
      "id": "8",
      "leagueId": "nhl",
      "name": "Los Angeles Kings",
      "abbreviation": "LA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/la.png"
    },
    {
      "id": "30",
      "leagueId": "nhl",
      "name": "Minnesota Wild",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/min.png"
    },
    {
      "id": "10",
      "leagueId": "nhl",
      "name": "Montreal Canadiens",
      "abbreviation": "MTL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/mtl.png"
    },
    {
      "id": "27",
      "leagueId": "nhl",
      "name": "Nashville Predators",
      "abbreviation": "NSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/nsh.png"
    },
    {
      "id": "11",
      "leagueId": "nhl",
      "name": "New Jersey Devils",
      "abbreviation": "NJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/nj.png"
    },
    {
      "id": "12",
      "leagueId": "nhl",
      "name": "New York Islanders",
      "abbreviation": "NYI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/nyi.png"
    },
    {
      "id": "13",
      "leagueId": "nhl",
      "name": "New York Rangers",
      "abbreviation": "NYR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png"
    },
    {
      "id": "14",
      "leagueId": "nhl",
      "name": "Ottawa Senators",
      "abbreviation": "OTT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/ott.png"
    },
    {
      "id": "15",
      "leagueId": "nhl",
      "name": "Philadelphia Flyers",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/phi.png"
    },
    {
      "id": "16",
      "leagueId": "nhl",
      "name": "Pittsburgh Penguins",
      "abbreviation": "PIT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/pit.png"
    },
    {
      "id": "18",
      "leagueId": "nhl",
      "name": "San Jose Sharks",
      "abbreviation": "SJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/sj.png"
    },
    {
      "id": "124292",
      "leagueId": "nhl",
      "name": "Seattle Kraken",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/sea.png"
    },
    {
      "id": "19",
      "leagueId": "nhl",
      "name": "St. Louis Blues",
      "abbreviation": "STL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/stl.png"
    },
    {
      "id": "20",
      "leagueId": "nhl",
      "name": "Tampa Bay Lightning",
      "abbreviation": "TB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/tb.png"
    },
    {
      "id": "21",
      "leagueId": "nhl",
      "name": "Toronto Maple Leafs",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/tor.png"
    },
    {
      "id": "129764",
      "leagueId": "nhl",
      "name": "Utah Mammoth",
      "abbreviation": "UTAH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/utah.png"
    },
    {
      "id": "22",
      "leagueId": "nhl",
      "name": "Vancouver Canucks",
      "abbreviation": "VAN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/van.png"
    },
    {
      "id": "37",
      "leagueId": "nhl",
      "name": "Vegas Golden Knights",
      "abbreviation": "VGK",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/vgk.png"
    },
    {
      "id": "23",
      "leagueId": "nhl",
      "name": "Washington Capitals",
      "abbreviation": "WSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/wsh.png"
    },
    {
      "id": "28",
      "leagueId": "nhl",
      "name": "Winnipeg Jets",
      "abbreviation": "WPG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/nhl/500/wpg.png"
    }
  ],
  "mls": [
    {
      "id": "18418",
      "leagueId": "mls",
      "name": "Atlanta United FC",
      "abbreviation": "ATL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png"
    },
    {
      "id": "20906",
      "leagueId": "mls",
      "name": "Austin FC",
      "abbreviation": "ATX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/20906.png"
    },
    {
      "id": "9720",
      "leagueId": "mls",
      "name": "CF Montréal",
      "abbreviation": "MTL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/9720.png"
    },
    {
      "id": "21300",
      "leagueId": "mls",
      "name": "Charlotte FC",
      "abbreviation": "CLT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/21300.png"
    },
    {
      "id": "182",
      "leagueId": "mls",
      "name": "Chicago Fire FC",
      "abbreviation": "CHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/182.png"
    },
    {
      "id": "184",
      "leagueId": "mls",
      "name": "Colorado Rapids",
      "abbreviation": "COL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/184.png"
    },
    {
      "id": "183",
      "leagueId": "mls",
      "name": "Columbus Crew",
      "abbreviation": "CLB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/183.png"
    },
    {
      "id": "193",
      "leagueId": "mls",
      "name": "D.C. United",
      "abbreviation": "DC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/193.png"
    },
    {
      "id": "18267",
      "leagueId": "mls",
      "name": "FC Cincinnati",
      "abbreviation": "CIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/18267.png"
    },
    {
      "id": "185",
      "leagueId": "mls",
      "name": "FC Dallas",
      "abbreviation": "DAL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/185.png"
    },
    {
      "id": "6077",
      "leagueId": "mls",
      "name": "Houston Dynamo FC",
      "abbreviation": "HOU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/6077.png"
    },
    {
      "id": "20232",
      "leagueId": "mls",
      "name": "Inter Miami CF",
      "abbreviation": "MIA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png"
    },
    {
      "id": "187",
      "leagueId": "mls",
      "name": "LA Galaxy",
      "abbreviation": "LA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/187.png"
    },
    {
      "id": "18966",
      "leagueId": "mls",
      "name": "LAFC",
      "abbreviation": "LAFC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png"
    },
    {
      "id": "17362",
      "leagueId": "mls",
      "name": "Minnesota United FC",
      "abbreviation": "MIN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/17362.png"
    },
    {
      "id": "18986",
      "leagueId": "mls",
      "name": "Nashville SC",
      "abbreviation": "NSH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/18986.png"
    },
    {
      "id": "189",
      "leagueId": "mls",
      "name": "New England Revolution",
      "abbreviation": "NE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/189.png"
    },
    {
      "id": "17606",
      "leagueId": "mls",
      "name": "New York City FC",
      "abbreviation": "NYC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png"
    },
    {
      "id": "12011",
      "leagueId": "mls",
      "name": "Orlando City SC",
      "abbreviation": "ORL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/12011.png"
    },
    {
      "id": "10739",
      "leagueId": "mls",
      "name": "Philadelphia Union",
      "abbreviation": "PHI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/10739.png"
    },
    {
      "id": "9723",
      "leagueId": "mls",
      "name": "Portland Timbers",
      "abbreviation": "POR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/9723.png"
    },
    {
      "id": "4771",
      "leagueId": "mls",
      "name": "Real Salt Lake",
      "abbreviation": "RSL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/4771.png"
    },
    {
      "id": "190",
      "leagueId": "mls",
      "name": "Red Bull New York",
      "abbreviation": "RBNY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/190.png"
    },
    {
      "id": "22529",
      "leagueId": "mls",
      "name": "San Diego FC",
      "abbreviation": "SD",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/22529.png"
    },
    {
      "id": "191",
      "leagueId": "mls",
      "name": "San Jose Earthquakes",
      "abbreviation": "SJ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/191.png"
    },
    {
      "id": "9726",
      "leagueId": "mls",
      "name": "Seattle Sounders FC",
      "abbreviation": "SEA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png"
    },
    {
      "id": "186",
      "leagueId": "mls",
      "name": "Sporting Kansas City",
      "abbreviation": "SKC",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/186.png"
    },
    {
      "id": "21812",
      "leagueId": "mls",
      "name": "St. Louis CITY SC",
      "abbreviation": "STL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/21812.png"
    },
    {
      "id": "7318",
      "leagueId": "mls",
      "name": "Toronto FC",
      "abbreviation": "TOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png"
    },
    {
      "id": "9727",
      "leagueId": "mls",
      "name": "Vancouver Whitecaps",
      "abbreviation": "VAN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png"
    }
  ]
};
